Machine option for build init

diff --git a/init-build b/init-build
--- a/init-build
+++ b/init-build
@@ -1,15 +1,43 @@
 #!/bin/bash
 
+MACHINE="raspberrypi0-2w-64"
+
+help()
+{
+    echo "Usage: $0 [-m <pi02w|pi3>]"
+    exit 1;
+}
+
+while getopts 'm:h' OPTION; do
+    case "${OPTION}" in
+        m)
+            case "${OPTARG}" in
+                pi02w)
+                    MACHINE=raspberrypi0-2w-64
+                    ;;
+                pi3)
+                    MACHINE=raspberrypi3-64
+                    ;;
+                *)
+                    echo "Invalid machine passed"
+                    help
+                    ;;
+            esac
+            ;;
+        h)
+            help
+            ;;
+    esac
+done
+
 if [ ! -d build/conf ];then
     mkdir -p build/conf
 fi
 
-if [ ! -f build/conf/bblayers.conf ]; then
-    cp conf/bblayers.conf build/conf
-fi
+cp conf/bblayers.conf build/conf
+cp conf/local.conf build/conf
 
-if [ ! -f build/conf/local.conf ]; then
-    cp conf/local.conf build/conf
-fi
+echo "Configure Build for machine: ${MACHINE}"
+sed -i "s/MACHINE = \"\"/MACHINE = \"${MACHINE}\"/g" build/conf/local.conf
 
 . layer/poky/oe-init-build-env build
